# Generated by Django 4.2.6 on 2024-03-13 19:17

import Utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomConnectAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='audio_files/', validators=[Utils.models.validate_mp3])),
            ],
        ),
    ]
