# Generated by Django 5.0.3 on 2024-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=255)),
                ('correct_answer', models.SmallIntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
