# Generated by Django 4.2.6 on 2024-03-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='roles',
        ),
        migrations.AddField(
            model_name='member',
            name='minutes_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
