# Generated by Django 4.2.6 on 2024-03-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_remove_member_roles_member_minutes_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Members.role')),
                ('game_assigned', models.CharField(max_length=50)),
                ('game_detection_string', models.CharField(max_length=255)),
            ],
            bases=('Members.role',),
        ),
    ]
