# Generated by Django 4.2.6 on 2024-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_gamerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='configurator',
            field=models.BooleanField(default=False),
        ),
    ]
