# Generated by Django 5.0.3 on 2024-03-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_member_configurator'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nicknames',
            field=models.CharField(default='', max_length=250),
        ),
    ]
