# Generated by Django 5.0.3 on 2024-03-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormatableMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AlcoholRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='AudiRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='DefaultMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='DefaultUserRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='GlucoseRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='GreetingsRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='GrubassyRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='JuliaRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='PbRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
    ]
