# Generated by Django 5.0.3 on 2024-03-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_member_nicknames'),
        ('Responses', '0002_remove_userformatablemessage_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuserrelatedmessage',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.member'),
        ),
    ]
