# Generated by Django 5.0.3 on 2024-04-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_member_nicknames'),
        ('Responses', '0003_defaultuserrelatedmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefaultMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.role')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
    ]
