# Generated by Django 5.0.3 on 2024-04-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responses', '0004_roledefaultmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmelkaRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='GoodbyeRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
        migrations.CreateModel(
            name='TroterRelatedMessage',
            fields=[
                ('userformatablemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Responses.userformatablemessage')),
            ],
            bases=('Responses.userformatablemessage',),
        ),
    ]
